# Generated by Django 6.0.4 on 2026-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_city_weatherrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='action_taken',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('logged', 'Logged'), ('ignored', 'Ignored')], default='logged', max_length=20),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='packet_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
